[[plugins]]
package = "@netlify/plugin-sitemap"

[build.environment]
  NODE_ENV = "development"

[build]
command = "npm run build"
publish = "_site"
functions = "netlify/functions"

[[redirects]]
  from = "/old-path"
  to = "/new-path"
  status = 301

  [[headers]]
  for = "/success-cv"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://www.google.com/recaptcha/; style-src 'self' 'unsafe-inline';"
    X-Netlify-Form-Size-Limit = "200000"