backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/img/blog"
public_folder: "/assets/img/blog"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/blog/posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }